[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.12"
prost = "0.13"
tokio = { version = "1.0", features = ["full"] } # asynchron
tokio-stream = "0.1"
serde = { version = "1.0", features = ["derive"] } # JSON
serde_json = "1.0"
crossbeam = "0.8"
uuid = { version = "1", features = ["v4"]}
pathfinding = "4"

[build-dependencies]
tonic-build = "0.12"