FROM rust:1-slim

RUN apt-get update && apt-get install -y protobuf-compiler && rm -rf /var/lib/apt/lists/*
RUN cargo install cargo-watch

WORKDIR /workspace/apps/engine

EXPOSE 50051

CMD ["cargo", "watch", "-x", "run"]
